# Generated by Django 5.2 on 2025-05-04 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.categories')),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.teams')),
            ],
        ),
    ]
